#==========================================================================
# Description: Build Armbian For Amlogic s9xxx tv box
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: build hybridELEC

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      elec_url:
        description: "Set elec path."
        required: false
        default: ""

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          #LibreELEC
          sudo apt install gcc make git unzip wget xz-utils bc gperf zip g++ xfonts-utils xsltproc openjdk-11-jre-headless -y
          #CoreELEC
          sudo apt install libparse-yapp-perl gperf xfonts-utils libxml-parser-perl patchutils lzop -y
          #EmuELEC
          sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc -y
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          cd /workdir
          # clone the repo
          git clone https://github.com/7Ji/HybridELEC
          cd HybridELEC
          # set some shared environment variables
          export PROJECT=Amlogic-ce
          export DEVICE=Amlogic-ng

          # optionally set builder name
          export BUILDER_NAME=xiayang

          # checkout the CoreELEC branch
          git checkout coreelec-19

          # set version for CoreELEC
          export HYBRID_VERSION_CE=19.4-Matrix
          export CUSTOM_VERSION=${HYBRID_VERSION_CE}-hybrid

          # build CE kernel and system images
          make system

          # checkout the EmuELEC branch
          git checkout emuelec-4.5
          # set version for EmuELEC
          export HYBRID_VERSION_EE=v4.5
          export CUSTOM_VERSION=${HYBRID_VERSION_EE}-hybrid

          # build EE kernel and system images
          make system

          # get back to the main branch
          git checkout hybrid-ng

          # combine the image
          make
          
          # sha256sum
          IMAGE_TARGET_compressed="$DIR_TARGET/HybridELEC-$DEVICE-CE_${HYBRID_VERSION_CE}_EE_$HYBRID_VERSION_EE.img.gz"
          sha256sum $IMAGE_TARGET_compressed > $IMAGE_TARGET_compressed.sha256

      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          artifacts: "/workdir/HybridELEC/target/*.gz,/workdir/HybridELEC/target/*.sha256"
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is hybridELEC image for Amlogic sbc
            * Firmware information
            Default username:
            Default password:
            Install to EMMC command: 
            Update command: 


